application: yjltest
version: 1
runtime: python
api_version: 1

handlers:
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /i18n
  script: i18n.py

- url: /gentoo/updateforumsfeed.*
  script: gentoo.py
  login: admin

- url: /gentoo/.*
  script: gentoo.py

- url: /src_lb.*
  script: src_lb.py

- url: /t_lb.*
  script: t_lb.py

- url: /test
  script: test.py

- url: /_ah/queue/deferred
  script: $PYTHON_LIB/google/appengine/ext/deferred/handler.py
  login: admin

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /twitter_blocklist
  script: twitter_block.py
  secure: always
