application: yjltest
version: 1
runtime: python
api_version: 1

handlers:
- url: /i18n
  script: i18n.py

- url: /gentoo/updateforumsfeed.*
  script: gentoo.py
  login: admin

- url: /gentoo/.*
  script: gentoo.py

- url: /src_lb.*
  script: src_lb.py

- url: /_ah/queue/deferred
  script: $PYTHON_LIB/google/appengine/ext/deferred/handler.py
  login: admin

- url: /twitter_blocklist
  script: twitter_block.py
  secure: always
